### ISSUE TITLE
Web browser testing support

### ISSUE THREAD

**Issue by thejhh** [sendanor/norjs#1]
Currently our Travis-CI configuration is using mocha and NodeJS directly for unit tests.

There is initial Karma configuration, but it is not finished.

We need to test browsers, too.

* [ ]  [#9 Initial unit test for NorJS component in browser](../issues/9)
* [ ]  [#3 IE support](../issues/3)
* [ ]  [#4 Chrome support](../issues/4)
* [ ]  [#5 Firefox support](../issues/5)
* [ ]  [#6 Safari support](../issues/6)
